apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: NodePort               # <--- Add this line
  selector:
    app: hello
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
